name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sinfonia-politica    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '/home/runner/work/proy_sp/wwwroot'    # set this to the path to your web app project
  NODE_VERSION: '20.x'                    # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: npm install and build
        run: |
          cd backend
          npm ci
          npm run build --if-present

      # Crear directorio de salida
      - name: Create output directory
        run: mkdir -p output

      # Preparar archivos para el deployment
      - name: Setup deployment files
        run: |
          echo "Configurando estructura del proyecto..."
          
          # Crear estructura de directorios
          mkdir -p output/public
          mkdir -p output/backend
          
          # Copiar archivos frontend a public
          echo "Copiando archivos frontend..."
          cp -r public/* output/public/
          
          # Copiar archivos backend
          echo "Copiando archivos backend..."
          cp backend/package*.json output/backend/
          cp backend/index.js output/backend/
          
          # Instalar dependencias
          cd output/backend
          npm ci --production
          
          echo "Verificando estructura:"
          ls -R output/
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: output
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: deploy

      - name: Set up deployment
        run: |
          echo "Configurando deployment..."
          
          # Crear estructura en wwwroot
          mkdir -p /home/runner/work/proy_sp/wwwroot
          
          # Copiar todo manteniendo la estructura
          cp -r deploy/* /home/runner/work/proy_sp/wwwroot/
          
          echo "Verificando estructura final:"
          tree /home/runner/work/proy_sp/wwwroot || ls -R /home/runner/work/proy_sp/wwwroot
          
      - name: Display deployment structure
        run: |
          echo "Contenido del directorio wwwroot:"
          ls -la /home/runner/work/proy_sp/wwwroot
          echo ""
          echo "Verificando archivos principales:"
          ls -l /home/runner/work/proy_sp/wwwroot/index.html
          ls -l /home/runner/work/proy_sp/wwwroot/images/Logo\ SP-11.png
          
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: /home/runner/work/proy_sp/wwwroot
