name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sinfonia-politica    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'backend'    # set this to the path to your web app project
  NODE_VERSION: '20.x'                    # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: npm install and build
        working-directory: ./backend
        run: |
          npm ci
          npm run build --if-present
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: backend

      - name: Set up deployment
        run: |
          mkdir -p /home/runner/work/proy_sp/backend
          cp -r backend/* /home/runner/work/proy_sp/backend/
          cd /home/runner/work/proy_sp/backend
          npm ci --only=production
          
      - name: Display structure of downloaded files
        run: |
          echo "Current directory structure:"
          ls -R /home/runner/work/proy_sp
          echo "Backend directory contents:"
          ls -la /home/runner/work/proy_sp/backend
          echo "Node.js version:"
          node --version
          echo "Package.json contents:"
          cat /home/runner/work/proy_sp/backend/package.json
          
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: /home/runner/work/proy_sp/backend
