name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sinfonia-politica-dbemamf9hsfrfxb5    # set this to your application's name

  NODE_VERSION: '20.x'                    # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Prepare deployment files
        run: |
          echo "🔨 Preparando archivos para deployment..."
          
          # 1. Crear directorio de salida y copiar todo el proyecto
          echo "📁 Copiando archivos..."
          mkdir -p dist
          cp -r . dist/
          
          # 2. Limpiar archivos innecesarios
          cd dist
          rm -rf .git .github
          
          # 3. Instalar dependencias de producción
          echo "📦 Instalando dependencias..."
          npm ci --production
          
          # 4. Verificar estructura final
          echo "✅ Verificando estructura final:"
          echo "Archivos en raíz:"
          ls -la
          echo "Contenido de public/:"
          ls -la public
          echo "Contenido de backend/:"
          ls -la backend
          
          # 5. Verificar que los archivos críticos existen
          if [ ! -f "backend/index.js" ]; then
            echo "❌ Error: No se encuentra backend/index.js"
            exit 1
          fi
          if [ ! -f "public/index.html" ]; then
            echo "❌ Error: No se encuentra public/index.html"
            exit 1
          fi
          if [ ! -f "web.config" ]; then
            echo "❌ Error: No se encuentra web.config"
            exit 1
          fi
          
          echo "✅ Todos los archivos críticos encontrados"
          
          # 4. Copiar web.config
          echo "📄 Copiando web.config..."
          cp ../web.config .
          
          # 5. Verificar estructura final
          echo "✅ Verificando estructura final:"
          ls -la
          echo "Contenido de public/:"
          ls -la public
          echo "Contenido de backend/:"
          ls -la backend
        
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-files
          path: .

      - name: Display deployment files
        run: |
          echo "📁 Estructura del deployment:"
          ls -R
          echo ""
          echo "📄 Verificando archivos principales:"
          ls -l index.html
          ls -l images/Logo\ SP-11.png
          ls -l backend/index.js
          ls -l web.config
          
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: 'Wait for deployment'
        run: |
          echo "⏳ Esperando 30 segundos para que la aplicación se inicie..."
          sleep 30

      - name: 'Verify Health Check'
        run: |
          echo "🔍 Verificando health check..."
          HEALTH_CHECK_URL="https://sinfonia-politica-dbemamf9hsfrfxb5.brazilsouth-01.azurewebsites.net/health"
          
          response=$(curl -s -w "\\n%{http_code}" $HEALTH_CHECK_URL)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Código HTTP: $http_code"
          echo "Respuesta: $body"
          
          if [ "$http_code" = "200" ]; then
            echo "✅ Health check exitoso"
          else
            echo "❌ Health check falló"
            exit 1
          fi
