name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sinfonia-politica-dbemamf9hsfrfxb5    # set this to your application's name

  NODE_VERSION: '20.x'                    # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Prepare deployment files
        run: |
          echo "🔨 Preparando archivos para deployment..."
          
          # Crear directorio de salida
          mkdir -p dist
          
          # 1. Copiar frontend (archivos estáticos)
          echo "📁 Copiando archivos frontend..."
          cp -r public/* dist/
          echo "Contenido copiado a dist:"
          ls -la dist/
          
          # 2. Preparar backend
          echo "📁 Configurando backend..."
          mkdir -p dist/backend
          cp backend/index.js dist/backend/
          cp package*.json dist/
          
          # 3. Instalar dependencias de producción
          echo "📦 Instalando dependencias..."
          cd dist
          npm install --omit=dev
          
          # 4. Copiar web.config
          echo "📄 Copiando web.config..."
          cp ../web.config .
          
          # 5. Verificar estructura final
          echo "✅ Verificando estructura final:"
          ls -la
          echo "Contenido de public/:"
          ls -la public
          echo "Contenido de backend/:"
          ls -la backend
        
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-files
          path: .

      - name: Display deployment files
        run: |
          echo "📁 Estructura del deployment:"
          ls -R
          echo ""
          echo "📄 Verificando archivos principales:"
          ls -l index.html
          ls -l images/Logo\ SP-11.png
          ls -l backend/index.js
          ls -l web.config
          
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
